runtime: python311
service: default

handlers:
# Serve static files
- url: /assets
  static_dir: assets
  secure: always

- url: /portals
  static_dir: portals
  secure: always

- url: /(.+\.html)
  static_files: \1
  upload: .+\.html
  secure: always

- url: /(.+\.css)
  static_files: \1
  upload: .+\.css
  secure: always

- url: /(.+\.js)
  static_files: \1
  upload: .+\.js
  secure: always

- url: /(.+\.png)
  static_files: \1
  upload: .+\.png
  secure: always

- url: /(.+\.ico)
  static_files: \1
  upload: .+\.ico
  secure: always

# Default to index.html
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
