runtime: python311
service: api
entrypoint: gunicorn -b :$PORT run:app

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2

env_variables:
  FLASK_ENV: "production"
  DB_USER: joitex_user
  DB_PASSWORD: Joitex_database@123
  DB_NAME: joitex_db
  DB_SOCKET: /cloudsql/joitex:asia-south1:joitex-mysql

beta_settings:
  cloud_sql_instances: joitex:asia-south1:joitex-mysql
