runtime: python311
service: api
entrypoint: gunicorn -b :$PORT run:app

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65

env_variables:
  FLASK_ENV: "production"
  SQLALCHEMY_DATABASE_URI: "sqlite:///app.db"
  # Set these via: gcloud app deploy --set-env-vars="SECRET_KEY=xxx,JWT_SECRET_KEY=xxx"
